site_name: bemani guide
copyright: fumo.photos Team
site_description: Bemani Troubleshooting Guide
site_author: IIDX Player
repo_url: https://github.com/yxrei/bemani-guide
repo_name: GitHub

nav:
    - Home: index.md
    - Games:
        - 'IIDX':
            - 'IIDX 9 [Btools]':
                - 'First Time Setup': 'games/iidx9/setup.md'
                - 'Common Problems/Tips': 'games/iidx9/problems.md'
            - 'IIDX 24':
                - 'First Time Setup': 'games/iidx24/setup.md'
                - 'Common Problems/Tips': 'games/iidx24/problems.md'
                - 'Hex Edits': 'games/iidx24/hexedits.md'
            - 'IIDX 25':
                - 'First Time Setup': 'games/iidx25/setup.md'
                - 'Common Problems/Tips': 'games/iidx25/problems.md'
                - 'Hex Edits': 'games/iidx25/hexedits.md'
            - 'IIDX 26':
                - 'First Time Setup': 'games/iidx26/setup.md'
                - 'Common Problems/Tips': 'games/iidx26/problems.md'
                - 'Hex Edits': 'games/iidx26/hexedits.md'
            - 'IIDX 27':
                - 'First Time Setup': 'games/iidx27/setup.md'
                - 'Common Problems/Tips': 'games/iidx27/problems.md'
                - 'Lightning Mode Specifics': 'games/iidx27/lightning.md'
        - 'SDVX':
            - 'SDVX IV':
                - 'First Time Setup': 'games/sdvx4/setup.md'
                - 'Common Problems/Tips': 'games/sdvx4/problems.md'
                - 'Hex Edits': 'games/sdvx4/hexedits.md'
            - 'SDVX V':
                - 'First Time Setup': 'games/sdvx5/setup.md'
                - 'Common Problems/Tips': 'games/sdvx5/problems.md'
                - 'Hex Edits': 'games/sdvx5/hexedits.md'
        - 'Pop&apos;n':
            - 'Pop&apos;n Usaneko':
                - 'First Time Setup': 'games/popnusaneko/setup.md'
                - 'Common Problems/Tips': 'games/popnusaneko/problems.md'
                - 'Hex Edits': 'games/popnusaneko/hexedits.md'
            - 'Pop&apos;n Peace':
                - 'First Time Setup': 'games/popnpeace/setup.md'
                - 'Common Problems/Tips': 'games/popnpeace/problems.md'
                - 'Hex Edits': 'games/popnpeace/hexedits.md'
            - 'HELLO Pop&apos;n':
                - 'First Time Setup': 'games/hellopopn/setup.md'
                - 'Common Problems/Tips': 'games/hellopopn/problems.md'
        - 'DDR':
            - 'DDR Ace':
                - 'First Time Setup': 'games/ddrace/setup.md'
                - 'Common Problems/Tips': 'games/ddrace/problems.md'
                - 'Hex Edits': 'games/ddrace/hexedits.md'
        - 'Jubeat':
            - 'Jubeat Clan':
                - 'First Time Setup': 'games/jubeatclan/setup.md'
                - 'Common Problems/Tips': 'games/jubeatclan/problems.md'
                - 'Hex Edits': 'games/jubeatclan/hexedits.md'
        - 'GITADORA':
            - 'GITADORA Matixx':
                - 'First Time Setup': 'games/gitamatixx/setup.md'
                - 'Common Problems/Tips': 'games/gitamatixx/problems.md'
                - 'Hex Edits': 'games/gitamatixx/hexedits.md'
            - 'GITADORA EXCHAIN':
                - 'First Time Setup': 'games/exchain/setup.md'
                - 'Common Problems/Tips': 'games/exchain/problems.md'
                - 'Hex Edits': 'games/exchain/hexedits.md'
        - 'Reflec Beat':
            - 'Reflec Beat: Reflesia':
                - 'First Time Setup': 'games/reflesia/setup.md'
                - 'Common Problems/Tips': 'games/reflesia/problems.md'
                - 'Hex Edits': 'games/reflesia/hexedits.md'
        - 'NOSTALGIA':
            - 'Nostalgia FORTE':
                - 'First Time Setup': 'games/nostforte/setup.md'
                - 'Common Problems/Tips': 'games/nostforte/problems.md'
                - 'Hex Edits': 'games/nostforte/hexedits.md'
            - 'Nostalgia Op.2':
                - 'First Time Setup': 'games/nostop2/setup.md'
                - 'Common Problems/Tips': 'games/nostop2/problems.md'
                - 'Hex Edits': 'games/nostop2/hexedits.md'
        - 'BeatStream アニムトライヴ':
                - 'First Time Setup': 'games/beatstreamfinal/setup.md'
                - 'Common Problems/Tips': 'games/beatstreamfinal/problems.md'
                - 'Hex Edits': 'games/beatstreamfinal/hexedits.md'
        - 'MÚSECA 1+1/2':
                - 'First Time Setup': 'games/musecafinal/setup.md'
                - 'Common Problems/Tips': 'games/musecafinal/problems.md'
                - 'Hex Edits': 'games/musecafinal/hexedits.md'
    - Error Codes: errorcodes.md
    - Extras:
        - 'Beginner Guide to Hex Editing': 'extras/hexguide.md'
        - 'Notes on the Most Common ASCs and Vendors': 'extras/ascs.md'
        - 'Arcade Parts List and Documentation': 'extras/parts.md'
        - 'SpiceTools Usage, Parameters, and Functionality': 'extras/spiceguide.md'
        - 'SpiceTools Error Messages': 'extras/spiceerrors.md'
        - 'List of Touchscreen Monitors and their Polling Rates': 'extras/pollingrates.md'
        - 'Exclusive Audio Workarounds': 'extras/streamaudio.md'
    - External Resources: externalresources.md
    - About: about.md

theme:
    name: material
    logo: img/bemani.png
    favicon: img/favicon.ico
    navigation_depth: 3
    palette:
        primary: deep purple
        scheme: slate

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.keys

plugins: []
