site_name: two-torial.xyz
copyright: two-torial Team
site_description: Arcade Games Troubleshooting Guide
site_author: two-torial Team
repo_url: https://github.com/two-torial/two-torial/
repo_name: GitHub

nav:
  - Home: index.md
  - Games:
    - BEMANI:
      - "beatmania IIDX":
        - "9th style":
          - "Game Setup": "games/iidx9/setup.md"
          - "Troubleshooting": "games/iidx9/troubleshooting.md"
        - "10th style":
          - "Game Setup": "games/iidx10/setup.md"
          - "Troubleshooting": "games/iidx10/troubleshooting.md"
        - "11 RED":
          - "Game Setup": "games/iidx11/setup.md"
          - "Troubleshooting": "games/iidx11/troubleshooting.md"
        - "12 HAPPY SKY":
          - "Game Setup": "games/iidx12/setup.md"
          - "Troubleshooting": "games/iidx12/troubleshooting.md"
        - "13 DistorteD":
          - "Game Setup": "games/iidx13/setup.md"
          - "Troubleshooting": "games/iidx13/troubleshooting.md"
        - "14 GOLD":
          - "Game Setup": "games/iidx14/setup.md"
          - "Troubleshooting": "games/iidx14/troubleshooting.md"
        - "24 SINOBUZ":
          - "First Time Setup": "games/iidx24/setup.md"
          - "Common Problems/Tips": "games/iidx24/problems.md"
        - "25 CANNON BALLERS":
          - "First Time Setup": "games/iidx25/setup.md"
          - "Common Problems/Tips": "games/iidx25/problems.md"
        - "26 Rootage":
          - "First Time Setup": "games/iidx26/setup.md"
          - "Common Problems/Tips": "games/iidx26/problems.md"
        - "27 HEROIC VERSE":
          - "First Time Setup": "games/iidx27/setup.md"
          - "Common Problems/Tips": "games/iidx27/problems.md"
          - "Lightning Mode Specifics": "games/iidx27/lightning.md"
        - "30 RESIDENT":
          - "Game Setup": "games/iidx30/setup.md"
          - "Extra Information": "games/iidx30/extras.md"
          - "Troubleshooting": "games/iidx30/troubleshooting.md"
        - "31 EPOLIS":
          - "Game Setup": "games/iidx31/setup.md"
          - "Extra Information": "games/iidx31/extras.md"
          - "Troubleshooting": "games/iidx31/troubleshooting.md"
        - "32 Pinky Crush":
          - "Game Setup": "games/iidx32/setup.md"
          - "Extra Information": "games/iidx32/extras.md"
          - "Troubleshooting": "games/iidx32/troubleshooting.md"
      - "Sound Voltex":
        - "IV HEAVENLY HAVEN":
          - "First Time Setup": "games/bemani/sdvx/4_heavenlyhaven/setup.md"
          - "Common Problems/Tips": "games/bemani/sdvx/4_heavenlyhaven/problems.md"
        - "V VIVID WAVE":
          - "First Time Setup": "games/bemani/sdvx/5_vividwave/setup.md"
          - "Common Problems/Tips": "games/bemani/sdvx/5_vividwave/problems.md"
        - "VI EXCEED GEAR":
          - "Game Setup": "games/bemani/sdvx/6_exceedgear/setup.md"
          - "Extra Information": "games/bemani/sdvx/6_exceedgear/extras.md"
          - "Troubleshooting": "games/bemani/sdvx/6_exceedgear/troubleshooting.md"
      - "Pop'n Music":
        - "Usaneko":
          - "First Time Setup": "games/popnusaneko/setup.md"
          - "Common Problems/Tips": "games/popnusaneko/problems.md"
        - "Peace":
          - "First Time Setup": "games/popnpeace/setup.md"
          - "Common Problems/Tips": "games/popnpeace/problems.md"
        - "HELLO!":
          - "First Time Setup": "games/hellopopn/setup.md"
          - "Common Problems/Tips": "games/hellopopn/problems.md"
      - "Dance Dance Revolution":
        - "A20":
          - "Game Setup": "games/bemani/ddr/a20/setup.md"
          - "Troubleshooting": "games/bemani/ddr/a20/troubleshooting.md"
        - "A20 PLUS":
          - "Game Setup": "games/bemani/ddr/a20plus/setup.md"
          - "Troubleshooting": "games/bemani/ddr/a20plus/troubleshooting.md"
        - "A3":
          - "Game Setup": "games/bemani/ddr/a3/setup.md"
          - "Troubleshooting": "games/bemani/ddr/a3/troubleshooting.md"
        - "WORLD":
          - "Game Setup": "games/bemani/ddr/world/setup.md"
          - "Troubleshooting": "games/bemani/ddr/world/troubleshooting.md"
      - "Jubeat":
        - "Clan":
          - "First Time Setup": "games/jubeatclan/setup.md"
          - "Common Problems/Tips": "games/jubeatclan/problems.md"
      - "GITADORA":
        - "Matixx":
          - "First Time Setup": "games/gitamatixx/setup.md"
          - "Common Problems/Tips": "games/gitamatixx/problems.md"
        - "EXCHAIN":
          - "First Time Setup": "games/exchain/setup.md"
          - "Common Problems/Tips": "games/exchain/problems.md"
        - "Fuzz-Up":
          - "Game Setup": "games/fuzzup/setup.md"
          - "Troubleshooting": "games/fuzzup/troubleshooting.md"
      - "Reflec Beat":
        - "Reflesia":
          - "First Time Setup": "games/reflesia/setup.md"
          - "Common Problems/Tips": "games/reflesia/problems.md"
      - "NOSTALGIA":
        - "FORTE":
          - "First Time Setup": "games/nostforte/setup.md"
          - "Common Problems/Tips": "games/nostforte/problems.md"
        - "Op.2":
          - "First Time Setup": "games/nostop2/setup.md"
          - "Common Problems/Tips": "games/nostop2/problems.md"
      - "BeatStream":
        - "アニムトライヴ":
          - "First Time Setup": "games/beatstreamfinal/setup.md"
          - "Common Problems/Tips": "games/beatstreamfinal/problems.md"
      - "MÚSECA":
        - "MÚSECA 1+1/2":
          - "First Time Setup": "games/musecafinal/setup.md"
          - "Common Problems/Tips": "games/musecafinal/problems.md"
    - SEGA:
      - "CHUNITHM":
        - "NEW":
          - "Game Setup": "games/sega/chunithm/new/setup.md"
          - "Controllers": "games/sega/chunithm/new/controllers.md"
          - "Cab-to-Cab": "games/sega/chunithm/new/c2c.md"
          - "Troubleshooting": "games/sega/chunithm/new/troubleshooting.md"
        - "NEW PLUS":
          - "Game Setup": "games/sega/chunithm/newplus/setup.md"
          - "Controllers": "games/sega/chunithm/newplus/controllers.md"
          - "Troubleshooting": "games/sega/chunithm/newplus/troubleshooting.md"
          - "Cab-to-Cab": "games/sega/chunithm/newplus/c2c.md"
        - "SUN":
          - "Game Setup": "games/sega/chunithm/sun/setup.md"
          - "Controllers": "games/sega/chunithm/sun/controllers.md"
          - "Troubleshooting": "games/sega/chunithm/sun/troubleshooting.md"
          - "Cab-to-Cab": "games/sega/chunithm/sun/c2c.md"
        - "SUN PLUS":
          - "Game Setup": "games/sega/chunithm/sunplus/setup.md"
          - "Controllers": "games/sega/chunithm/sunplus/controllers.md"
          - "Troubleshooting": "games/sega/chunithm/sunplus/troubleshooting.md"
          - "Cab-to-Cab": "games/sega/chunithm/sunplus/c2c.md"
        - "LUMINOUS":
          - "Game Setup": "games/sega/chunithm/luminous/setup.md"
          - "Controllers": "games/sega/chunithm/luminous/controllers.md"
          - "Troubleshooting": "games/sega/chunithm/luminous/troubleshooting.md"
          - "Cab-to-Cab": "games/sega/chunithm/luminous/c2c.md"
        - "LUMINOUS PLUS":
          - "Game Setup": "games/sega/chunithm/luminousplus/setup.md"
          - "Controllers": "games/sega/chunithm/luminousplus/controllers.md"
          - "Troubleshooting": "games/sega/chunithm/luminousplus/troubleshooting.md"
          - "Cab-to-Cab": "games/sega/chunithm/luminousplus/c2c.md"
        - "VERSE":
          - "Game Setup": "games/sega/chunithm/verse/setup.md"
          - "Controllers": "games/sega/chunithm/verse/controllers.md"
          - "Troubleshooting": "games/sega/chunithm/verse/troubleshooting.md"
          - "Cab-to-Cab": "games/sega/chunithm/verse/c2c.md"
      - "maimai DX":
        - "BUDDiES":
          - "Game Setup": "games/maimaidx/buddies/setup.md"
          - "Controllers": "games/maimaidx/buddies/controllers.md"
          - "Troubleshooting": "games/maimaidx/buddies/troubleshooting.md"
        - "PRiSM":
          - "Game Setup": "games/maimaidx/prism/setup.md"
          - "Controllers": "games/maimaidx/prism/controllers.md"
          - "Troubleshooting": "games/maimaidx/prism/troubleshooting.md"
        - "PRiSM PLUS":
          - "Game Setup": "games/maimaidx/prismplus/setup.md"
          - "Controllers": "games/maimaidx/prismplus/controllers.md"
          - "Troubleshooting": "games/maimaidx/prismplus/troubleshooting.md"
      - "O.N.G.E.K.I.":
        - "bright MEMORY":
          - "Game Setup": "games/ongekibrightmemory/setup.md"
          - "Controllers": "games/ongekibrightmemory/controllers.md"
          - "Troubleshooting": "games/ongekibrightmemory/troubleshooting.md"
        - "Re:Fresh":
          - "Game Setup": "games/ongekirefresh/setup.md"
          - "Controllers": "games/ongekirefresh/controllers.md"
          - "Troubleshooting": "games/ongekirefresh/troubleshooting.md"
      - "WACCA":
        - "Lily R":
          - "Game Setup": "games/waccalilyr/setup.md"
          - "Controllers": "games/waccalilyr/controllers.md"
        - "Reverse":
          - "Game Setup": "games/waccareverse/setup.md"
          - "Controllers": "games/waccareverse/controllers.md"
    - NAMCO:
      - "Taiko no Tatsujin: Nijiiro":
        - "Game Setup": "games/taikonijiiro/setup.md"
        - "Troubleshooting": "games/taikonijiiro/troubleshooting.md"
  - Error Codes:
    - BEMANI: "errorcodes/bemani.md"
    - SEGA: "errorcodes/sega.md"
  - Game Patching:
    - "Using Spice2x": "extras/patchsp2x.md"
    - "Using Web": "extras/patchweb.md"
    - "Manually": "extras/hexguide.md"
  - Extras:
    - "Data Mods & Omnimix": "extras/datamods.md"
    - "Asphyxia Core": "extras/asphyxia.md"
    - "WASAPI & ASIO": "extras/audio.md"
    - "Exclusive Audio Workarounds": "extras/streamaudio.md"
    - "Common ASCs & Vendors": "extras/ascs.md"
    - "Arcade Parts": "extras/parts.md"
    - "Touch Monitors & Polling Rates": "extras/pollingrates.md"
    - "SoftEther VPN for Cab-to-Cab": "extras/softether.md"
    - "Modding Unity-based games": "extras/unity.md"
  - Other Resources: resources.md

not_in_nav: |
  games/bemani/iidx/common
  games/bemani/sdvx/common
  games/bemani/ddr/common
  games/sega/chunithm/common
  games/mu3
  games/mercury
  games/mai2
  games/ddr

validation:
  links:
    absolute_links: relative_to_docs

theme:
  name: material
  custom_dir: overrides
  logo: img/two-torial/website-logo.svg
  favicon: img/favicon.ico
  icon:
    repo: fontawesome/brands/github
  navigation_depth: 3
  palette:
    # Toggle for auto mode
    - media: "(prefers-color-scheme)"
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html

plugins:
  - search
  - git-revision-date-localized

extra_css:
  - style.css

extra:
  analytics:
    provider: custom
    property: https://tuah-torial.goatcounter.com/count
