name: Build 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prep Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install pip deps
        run: |
          python -m pip install --user -r requirements.txt
      - name: Build and deploy site
        run: mkdocs gh-deploy --force